version: 2
updates:
  # Maintain dependencies for Pulpcore
  - package-ecosystem: "pip"
    directory: "/automation"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[dependabot]"
    # Add labels for dependabot bumps
    labels:
      - "dependabot"
    ignore:
      - dependency-name: "pulpcore*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-rpm*"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-ostree"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-python"
        update-types: ["version-update:semver-minor"]
      - dependency-name: "pulp-deb"
        update-types: ["version-update:semver-minor"]
